Help menu added. Commandline options added  Changes to be committed: 	modified:   update-system

diff --git a/update-system b/update-system
--- a/update-system
+++ b/update-system
@@ -1,16 +1,110 @@
 #!/bin/bash
 
-    # This program is free software: you can redistribute it and/or modify # it under the terms of the GNU General Public License as published by
-    # the Free Software Foundation, either version 3 of the License, or
-    # (at your option) any later version.
+################################################################
+# This program is free software: you can redistribute it and/or modify 
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
 
-    # This program is distributed in the hope that it will be useful,
-    # but WITHOUT ANY WARRANTY; without even the implied warranty of
-    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-    # GNU General Public License for more details.
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
 
-    # You should have received a copy of the GNU General Public License
-    # along with this program.  If not, see <https://www.gnu.org/licenses/>.
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+
+
+################################################################
+############################ INIT ##############################
+################################################################
+
+print_usage() {
+    echo "Usage: $(basename ${1}) COMMAND..."
+    echo "   or: $(basename ${1}) -h"
+    echo -e "\n Update components specified in COMMAND. Multiple commands can be separated by spaces."
+    echo " Whether a specified command runs or not is contingent on the component being available in the system."
+    echo -e "\nCommands:"
+    echo " d            Updates dnf packages"
+    echo " t            Updates apt pacakges"
+    echo " s            Updates snap packages"
+    echo " f            Updates flatpak packages"
+    echo " n            Updates npm global"
+    echo " p            Updates some python3 packages"
+    echo " g            Updates Ubuntu drivers (Nvidia)"
+    echo " a            Runs all of the above, whatever is available"
+    echo -e "\nSwitches:"
+    echo " -h           Prints this help menu and exits"
+}
+
+UPDATE_APT=0
+UPDATE_DNF=0
+UPDATE_SNAP=0
+UPDATE_FLAT=0
+UPDATE_NPM=0
+UPDATE_PY=0
+UPDATE_DRIV=0
+
+if [[ ${#} -eq 0 ]]
+then
+    echo -e "ERROR: No commands specified. Please specify one or more commands.\n"
+    print_usage ${0}
+    exit 1
+fi
+
+if [[ ${1} = "-h" ]]
+then
+    print_usage ${0}
+    exit 0
+fi
+
+for arg in ${@}
+do
+    case ${arg} in 
+        "a")
+            UPDATE_APT=1
+            UPDATE_DNF=1
+            UPDATE_SNAP=1
+            UPDATE_FLAT=1
+            UPDATE_NPM=1
+            UPDATE_PY=1
+            UPDATE_DRIV=1
+            break 
+            ;;
+        
+        "d")
+            UPDATE_DNF=1
+            ;;
+        "t")
+            UPDATE_APT=1
+            ;;
+        "s")
+            UPDATE_SNAP=1
+            ;;
+        "f")
+            UPDATE_FLAT=1
+            ;;
+        "g")
+            UPDATE_DRIV=1
+            ;;
+        "n")
+            UPDATE_NPM=1
+            ;;
+        "p")
+            UPDATE_PY=1
+            ;;
+        "-h")
+            print_usage ${0}
+            exit 0
+            ;;
+        *)
+            echo "Invalid command: ${arg}"
+            exit 1
+            ;;
+    esac
+done
+
+let UPDATE_COUNT=0
 
 
 ################################################################
@@ -20,8 +114,9 @@
 apt --version > /dev/null 2>&1 
 APT_EXISTS=${?}
 
-if [[ ${APT_EXISTS} -eq 0 ]]
+if [[ ${APT_EXISTS} -eq 0 && ${UPDATE_APT} -eq 1 ]]
 then
+    let UPDATE_COUNT++
     echo -e "\n===================================================================="
     echo -e " Updating Apt Packages"
     echo -e "====================================================================\n"
@@ -72,8 +167,9 @@ fi
 dnf --version > /dev/null 2>&1 
 DNF_EXISTS=${?}
 
-if [[ ${DNF_EXISTS} -eq 0 ]]
+if [[ ${DNF_EXISTS} -eq 0 && ${UPDATE_DNF} -eq 1 ]]
 then
+    let UPDATE_COUNT++
     echo -e "\n===================================================================="
     echo -e " Updating Dnf Packages"
     echo -e "====================================================================\n"
@@ -103,8 +199,9 @@ fi
 ubuntu-drivers -h > /dev/null 2>&1
 UBUNTU_DRIVERS_EXISTS=${?}
 
-if [[ ${UBUNTU_DRIVERS_EXISTS} -eq 0 ]] && [[ $(id -u) -eq 0  ]]
+if [[ ${UBUNTU_DRIVERS_EXISTS} -eq 0 && $(id -u) -eq 0 && ${UPDATE_DRIV} -eq 1 ]]
 then
+    let UPDATE_COUNT++
 	echo -e "\n===================================================================="
 	echo -e " Running ubuntu-drivers autoinstall..."
 	echo -e "====================================================================\n"
@@ -114,6 +211,7 @@ then
 	echo -e "--------------------------------------------------------------------\n"
 fi
 
+
 ################################################################
 ####################### SNAP UPDATE ############################
 ################################################################
@@ -121,8 +219,9 @@ fi
 snap --version > /dev/null 2>&1
 SNAP_EXISTS=${?}
 
-if [[ ${SNAP_EXISTS} -eq 0 ]]
+if [[ ${SNAP_EXISTS} -eq 0 && ${UPDATE_SNAP} -eq 1 ]]
 then
+    let UPDATE_COUNT++
 	echo -e "\n===================================================================="
 	echo -e " Running snap refresh..."
 	echo -e "====================================================================\n"
@@ -132,6 +231,7 @@ then
 	echo -e "--------------------------------------------------------------------\n"
 fi
 
+
 ################################################################
 ##################### FLATPAK UPDATE ###########################
 ################################################################
@@ -139,8 +239,9 @@ fi
 flatpak --version > /dev/null 2>&1
 FLATPAK_EXISTS=${?}
 
-if [[ ${FLATPAK_EXISTS} -eq 0 ]]
+if [[ ${FLATPAK_EXISTS} -eq 0 && ${UPDATE_FLAT} -eq 1 ]]
 then
+    let UPDATE_COUNT++
 	echo -e "\n===================================================================="
 	echo -e " Running flatpak update..."
 	echo -e "====================================================================\n"
@@ -150,6 +251,7 @@ then
 	echo -e "--------------------------------------------------------------------\n"
 fi
 
+
 ################################################################
 ######################### NPM UPDATE ###########################
 ################################################################
@@ -157,8 +259,9 @@ fi
 npm --version > /dev/null 2>&1
 NPM_EXISTS=${?}
 
-if [[ ${NPM_EXISTS} -eq 0 ]]
+if [[ ${NPM_EXISTS} -eq 0 && ${UPDATE_NPM} -eq 1 ]]
 then
+    let UPDATE_COUNT++
 	echo -e "\n===================================================================="
 	echo -e " Running npm update..."
 	echo -e "====================================================================\n"
@@ -169,6 +272,7 @@ then
 	echo -e "--------------------------------------------------------------------\n"
 fi
 
+
 ################################################################
 ######################### PYTHON UPDATE ########################
 ################################################################
@@ -177,8 +281,9 @@ PYTHON3="/usr/bin/python3"
 ${PYTHON3} --version > /dev/null 2>&1
 PYTHON_EXISTS=${?}
 
-if [[ ${PYTHON_EXISTS} -eq 0 ]]
+if [[ ${PYTHON_EXISTS} -eq 0 && ${UPDATE_PY} -eq 1 ]]
 then
+    let UPDATE_COUNT++
 	echo -e "\n===================================================================="
 	echo -e " Updating Python packages..."
 	echo -e "====================================================================\n"
@@ -193,46 +298,68 @@ fi
 ######################## STATUS MESSAGE ########################
 ################################################################
 
+if [[ ${UPDATE_COUNT} -eq 0 ]]
+then
+    echo "None of the selected components were found in the system."
+    exit 0
+fi
 
 echo -e "\n===================================================================="
 echo -e " Operations completed with the following exit codes:(0 = SUCCESS)"
 echo -e "====================================================================\n"
-if [[ ${APT_EXISTS} -eq 0 ]]
+if [[ ${APT_EXISTS} -eq 0 && ${UPDATE_APT} -eq 1 ]]
 then
     echo "APT UPDATE : ${UPDATE_EXIT_CODE}"
     echo "APT UPGRADE: ${UPGRADE_EXIT_CODE}"
+else
+    UPDATE_EXIT_COLDE=0
+    UPGRADE_EXIT_CODE=0
 fi
 
-if [[ ${DNF_EXISTS} -eq 0 ]]
+if [[ ${DNF_EXISTS} -eq 0 && ${UPDATE_DNF} -eq 1 ]]
 then
-    echo "DNF : ${DNF_UPDATE_EXIT_CODE}"
+    echo "DNF UPDATE  : ${DNF_UPDATE_EXIT_CODE}"
+else
+    DNF_UPDATE_EXIT_CODE=0
 fi
 
-if [ ${UBUNTU_DRIVERS_EXISTS} -eq "0" ]
+if [[ ${UBUNTU_DRIVERS_EXISTS} -eq 0 && $(id -u) -eq 0 && ${UPDATE_DRIV} -eq 1 ]]
 then
-	echo "NVIDIA : ${UBUNTU_DRIVERS_EXIT_CODE}"
+	echo "NVIDIA     : ${UBUNTU_DRIVERS_EXIT_CODE}"
+else
+    UBUNTU_DRIVERS_EXIT_CODE=0
 fi
 
-if [ ${SNAP_EXISTS} -eq "0" ]
+if [[ ${SNAP_EXISTS} -eq 0 && ${UPDATE_SNAP} -eq 1 ]]
 then
-	echo "SNAP   : ${SNAP_EXIT_CODE}"
+	echo "SNAP       : ${SNAP_EXIT_CODE}"
+else 
+    SNAP_EXIT_CODE=0
 fi
 
-if [ ${FLATPAK_EXISTS} -eq "0" ]
+if [[ ${FLATPAK_EXISTS} -eq 0 && ${UPDATE_FLAT} -eq 1 ]]
 then
-	echo "FLATPAK: ${FLATPAK_EXIT_CODE}"
+	echo "FLATPAK    : ${FLATPAK_EXIT_CODE}"
+else
+    FLATPAK_EXIT_CODE=0
 fi
 
-if [ ${NPM_EXISTS} -eq "0" ]
+if [[ ${NPM_EXISTS} -eq 0 && ${UPDATE_NPM} -eq 1 ]]
 then
-	echo "NPM    : ${NPM_EXIT_CODE}"
+	echo "NODE GLOBAL: ${NPM_EXIT_CODE}"
+else
+    NPM_EXIT_CODE=0
 fi
 
-if [ ${PYTHON_EXISTS} -eq "0" ]
+if [[ ${PYTHON_EXISTS} -eq 0 && ${UPDATE_PY} -eq 1 ]]
 then
-	echo "PIP    : ${PIP_EXIT_CODE}"
+	echo "PYTHON 3   : ${PIP_EXIT_CODE}"
+else
+    PIP_EXIT_CODE=0
 fi
+
 echo ""
-echo -e "\nDone"
+echo -e "\nTotal components for which update was run: ${UPDATE_COUNT}"
 echo -e "--------------------------------------------------------------------\n"
 
+exit ${UPDATE_EXIT_CODE} || ${UPGRADE_EXIT_CODE} || ${DNF_UPDATE_EXIT_CODE} || ${UBUNTU_DRIVERS_EXIT_CODE} || ${SNAP_EXIT_CODE} || ${FLATPAK_EXIT_CODE} || ${NPM_EXIT_CODE} || ${PIP_EXIT_CODE}
